- name: "Copy deploy ssh public key"
  hosts: all
  become: yes
  tasks:
    - name: "create .ssh directory"
      file:
        path: /home/deploy/.ssh
        owner: "deploy"
        group: "deploy"
        mode: "0700"
        state: "directory"
    - name: "copy public key as authorized_keys"
      copy:
        src: ./deploy_ed25519.pub
        dest: /home/deploy/.ssh/authorized_keys
        owner: deploy
        group: deploy
        mode: '0600'


