- name: "Install Docker"
  hosts: all
  become: yes
  tasks:
    - name: "updating packages and install ca-certificates and curl"
      apt:
        update_cache: yes
        pkg:
          - ca-certificates
          - curl
    - name: "install keyrings 
        
