- name: "Install Docker"
  hosts: all
  become: true
  block:
    - name: "updating packages and install ca-certificates and curl"
      apt:
        update_cache: yes
        pkg:
          - ca-certificates
          - curl
    - name: "create keyrings directory"
      file:
        path: /etc/apt/keyrings
        owner: root
        group: root
        mode: "0755"
        state: "directory"
    - name: "download docker.asc"
      command:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    - name: "make docker.asc readable"
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: a+r
    - name: "copy docker source file"
      copy:
        src: docker.sources
        dest: /etc/apt/sources.list.d/docker.sources
        owner: root
        group: root
        mode: "0644"
    - name: "update and install"
      apt:
        update_cache: yes
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
