- name: Deploy Inception
  hosts: all
  become: true
  tasks:
    - name: "install docker"
      include_role:
        name: "install_docker"

    - name: "deploy user"
      include_role:
        name: "deploy_user"

    - name: "install inception"
      include_role:
        name: "install_inception"
      vars:
        ansible_user: "deploy"
      ansible_user: "deploy"

    - name: "deploy inception"
      include_role:
        name: "deploy_inception"
