- name: Add user deploy to docker group 
  hosts: all
  become: true
  tasks:
    - name: add deploy to group docker 
      ansible.builtin.user:
        name: deploy
        groups: docker 
        append: yes 

