- name: Create user deploy
  hosts: all
  become: true
  tasks:
    - name: Add the user deploy
      ansible.builtin.user:
        name: deploy
        comment: ansible deploy
        create_home: yes
        shell: /bin/bash
        groups: sudo
        password: '!'

