sql_password: qPlDh9qLrkEePRwrsef1vIRdrTR73c20
sql_root_password: m6VcG8FOWLVhQIHihDSxRYq_XDiedJr0
wp_password: abcd
sql_database: thedb
sql_user: droopy
wp_title: Coconut
wp_username: droopy
wp_email: droopy@coconut.io
country: FR
state: Idf
city: Paris
org: CocoOil
org_unit: Max
cert_uid: 1234
